### ISSUE TITLE
Deploy 3.1 models to Replicate

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/granite-kitchen#38]

**Comment by bjhargrave** [comment]
[ibm-granite/granite-3.1-8b-instruct](https://replicate.com/ibm-granite/granite-3.1-8b-instruct) and [ibm-granite/granite-3.1-2b-instruct](https://replicate.com/ibm-granite/granite-3.1-2b-instruct) models are deployed to Replicate.
