### ISSUE TITLE
Update all kitchen recipes from 3.0 to 3.1 + add granite embeddings

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/granite-kitchen#39]
1. Embedding models are referenced here and should be updated https://github.com/ibm-granite-community/granite-kitchen/blob/main/recipes/Components/Langchain_Embeddings_Models.ipynb

2. The "Inference Platforms" notebooks linked to from the README should all update their default Granite model to 3.1 https://github.com/ibm-granite-community/granite-kitchen?tab=readme-ov-file#inference-platforms
 
3. Default models should be updated in the LangChain sections: https://github.com/ibm-granite-community/granite-kitchen/blob/main/recipes/Components/Langchain_LLMs.ipynb

**Comment by adampingel** [comment]
Updating embeddings is the top priority.

**Comment by bjhargrave** [comment]
Fixed by https://github.com/ibm-granite-community/granite-kitchen/pull/40
