### ISSUE TITLE
Update pip install line in Replicate recipe (and look for same issue elsewhere)

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/granite-kitchen#7]
The pip install should install granite-kitchen, not utils.

https://github.com/ibm-granite-community/granite-kitchen/blob/main/recipes/Getting_Started/Getting_Started_with_Replicate.ipynb

**Comment by adampingel** [comment]
Includes looking for all other instances where we have this problem.

**Comment by fayvor** [comment]
[PR up here](https://github.com/ibm-granite-community/granite-kitchen/pull/13).

**Comment by rawkintrevo** [comment]
See my last comment on PR. the kitchen is too fat. Merging that PR will make all testing in that repo fail.

**Comment by fayvor** [comment]
Checked the other repos (code, legal, snack) for utils installs, and there were none.
```
grep "community/utils" `find */recipes -name "*.ipynb"`|grep "pip install"
```

**Comment by rawkintrevo** [comment]
Yea, adam and I traced the issue to just that NH case law notebook, so we decided it was less urgent than we thought, and punt on the whole thing.
