### ISSUE TITLE
fix replicate 401

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-community/granite-kitchen#8]
The explicit setting of `REPLICATE_API_TOKEN` with get_env_var() is not working, since the env var is accessed somewhere implicitly during model invocation. We need to go back to set_env_var().                  

https://github.com/ibm-granite-community/granite-kitchen/blob/main/recipes/Getting_Started/Getting_Started_with_Replicate.ipynb

Also fix the https://github.com/ibm-granite-community/granite-kitchen/blob/main/recipes/Components/Langchain_LLMs.ipynb

Manually propagate the changes to recipes using Replicate in other repos.

**Comment by fayvor** [comment]
[PR](https://github.com/ibm-granite-community/utils/pull/18) - merged.
- [Getting Started with Replicate](https://colab.research.google.com/github/ibm-granite-community/granite-kitchen/blob/main/recipes/Getting_Started/Getting_Started_with_Replicate.ipynb) works on colab
- [RAG with Langchain](https://colab.research.google.com/github/ibm-granite-community/granite-snack-cookbook/blob/main/recipes/RAG/RAG_with_Langchain.ipynb#scrollTo=Ice-umx-E-30) works on colab
- [Text to Shell](https://colab.research.google.com/github/ibm-granite-community/granite-code-cookbook/blob/main/recipes/Text_to_Shell/Text_to_Shell.ipynb#scrollTo=QU2BnhxlFV2K) works on colab
